services:
  - type: web
    name: enviro-sat-api
    runtime: docker
    dockerfilePath: ./Dockerfile.backend
    plan: free
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        value: 10000
